name: GitHub Blog RSS to Discord

on:
  schedule:
    - cron: '0 */6 * * *'   # every 6 hours
  workflow_dispatch:

jobs:
  rss:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils jq curl

      - name: Fetch RSS and check new post
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          FEED_URL="https://github.blog/changelog/feed/"
          curl -s $FEED_URL > feed.xml

          TITLE=$(grep -oPm1 "(?<=<title>)[^<]+" feed.xml | sed -n '2p')
          LINK=$(grep -oPm1 "(?<=<link>)[^<]+" feed.xml | sed -n '2p')
          ID=$(grep -oPm1 "(?<=<guid>)[^<]+" feed.xml | sed -n '1p')


          OLD_ID=$(cat last_id.txt)

          if [ "$ID" != "$OLD_ID" ]; then
            curl -H "Content-Type: application/json" \
            -d "{\"content\":\"ðŸ†• **New GitHub Update Posted!**\n\n**$TITLE**\n$LINK\"}" \
            $WEBHOOK

            OLD_ID=$(cat last_id.txt || echo 0)

            git config user.name github-actions
            git config user.email github-actions@github.com
            git add last_id.txt
            git commit -m "Update last RSS ID"
            git push
          fi

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/omaga-24/wolfy-github-changelog-bot.git
          git add last_id.txt
          git commit -m "Update last RSS ID"
          git push origin HEAD:${GITHUB_REF##*/}

          
